
library(shiny)
library(shinydashboard)
library(dplyr)
library(ggplot2)
library(CausalImpact)
library(DT)
library(plotly)
library(shinycssloaders)
dashboard.header<-dashboardHeader(
  title = "Impact Calculator"
)

dashboard.sidebar<-dashboardSidebar(
  sidebarMenu(
    menuItem("Data Upload", tabName = "data-upload", icon = icon("upload", lib = "glyphicon")),
    menuItem("Covariate Validation", tabName = "covar-check", icon = icon("check")),
    menuItem("Impact Analysis", tabName = "impact-analysis", icon = icon("calculator")),
    menuItem("About", tabName = "about", icon = icon("info"))
  )
)

dashboard.body<-dashboardBody(
  tabItems(
    tabItem(tabName = "data-upload",
            fluidRow(
              box(title="Data File Upload", width=12, solidHeader = TRUE, status="primary",
                  p("Please select a csv file with the following headers: date (yyyy-mm-dd), response, x1....xn"),
                  fileInput("data.file.input",
                            label=NULL,
                            multiple = FALSE,
                            accept = c("text/csv",
                                       "text/comma-separated-values,text/plain",
                                       ".csv"))
              )
            ),
            fluidRow(
              column(width=3,
                     uiOutput("DateRange")
              ),
              column(width=9,
                     uiOutput("original.time.series")
              )
            ),
            br(),
            fluidRow(
              column(width=3),
              column(width=9,uiOutput("data.table.output"))
            )
    ),
    tabItem(tabName = "covar-check",
            fluidRow(
              column(width=12,
                     uiOutput("covar.graph.container")
              )
            ),
            br(),
            fluidRow(
              column(width=2,
                     uiOutput("covariate.select")
              ),
              column(width=4,
                     uiOutput("summary.stats")
              ),
              column(width=4,
                     uiOutput("covariate.explanation")
              ),
              column(width=2)
            )
    ),
    tabItem(tabName = "impact-analysis",
            fluidRow(
              withSpinner(uiOutput("impact.plot.output"))
            ),
            br(),
            fluidRow(
              column(width=6,
                     uiOutput("impact.metrics")
              ),
              column(width=6,
                     uiOutput("impact.summary")
              )
            )
    ),
    tabItem(tabName = "about",
            fluidRow(
              column(width=10,
                     box(title="Full Impact Report", width=12, solidHeader = TRUE, status="primary",
                         tags$b("What does this application do?"),
                         p("This application is an interactive implementation of the R Package CausalImpact, which provides an approach to estimating the causal effect of a designed intervention on a time series. For example, how many additional daily clicks were generated by an advertising campaign? Answering a question like this can be difficult when a randomized experiment is not available."),
                         tags$b("How does it work?"),
                         p("Given a response time series (e.g., clicks) and a set of control time series (e.g., clicks in non-affected markets or clicks on other sites), the package constructs a Bayesian structural time-series model. This model is then used to try and predict the counterfactual, i.e., how the response metric would have evolved after the intervention if the intervention had never occurred."),
                         tags$b("What assumptions does the model make?"),
                         p("As with all non-experimental approaches to causal inference, valid conclusions require strong assumptions. In the case of CausalImpact, we assume that there is a set control time series that were themselves not affected by the intervention. If they were, we might falsely under- or overestimate the true effect. Or we might falsely conclude that there was an effect even though in reality there wasn’t. The model also assumes that the relationship between covariates and treated time series, as established during the pre-period, remains stable throughout the post-period")
                     )
              )
            )
    )
  )
)


ui <- dashboardPage(
  skin = "blue",
  dashboard.header,
  dashboard.sidebar,
  dashboard.body
)

server <- function(input, output, session) { 
  vline <- function(x = 0, color = "red") {
    list(
      type = "line", 
      y0 = 0, 
      y1 = 1, 
      yref = "paper",
      x0 = x, 
      x1 = x, 
      line = list(color = color)
    )
  }
  data<-reactive({
    inFile <- input$data.file.input
    
    if (!is.null(inFile)){
      dat<-read.csv(input$data.file.input$datapath)
      dat$date <- as.Date(dat$date, format = "%Y-%m-%d")
      return(as.data.frame(dat))
    }
  })
  covar.data<-reactive({
    req(input$data.file.input)
    df<-isolate(data())
    df$response<-NULL
    df$date<-NULL
    return(df)
  })
  impact<-reactive({
    req(input$data.file.input)
    zoo<-read.zoo(data(), format = "%Y-%m-%d")
    pre.period <- as.Date(c(min(data()$date), input$interventionrange[1]-1))
    post.period <- as.Date(c(input$interventionrange[1], input$interventionrange[2]))
    impact <- CausalImpact(zoo, pre.period, post.period)
    return(impact)
  })
  
  output$DateRange<-renderUI({
    req(input$data.file.input)
    tagList(
      box(title="Date Ranges", width=12, solidHeader = TRUE, status="primary",
          p("Please select the campaign period (Test data campaign is 3/9-4/9)"),
          fluidRow(
            column(width=12,
                   dateRangeInput("interventionrange", "Date range:",
                                  start = min(data()$date)+1,
                                  end   = max(data()$date)
                   )
            )
          )
      )
    )
  })
  
  output$data.output <- renderPlotly({
    req(input$data.file.input)
    plot_ly(data(), x=~date, y=~response, type="scatter", mode="lines") %>%
      layout(shapes = list(vline(toString(input$interventionrange[1])),vline(toString(input$interventionrange[2]))))
  })
  
  output$original.time.series<-renderUI({
    req(input$data.file.input)
    box(title="Customer Transactions Over Time", width=12, solidHeader = TRUE, status="primary",
        plotlyOutput("data.output")
    )
  })
  
  output$data.table.output <- renderUI({c
    req(input$data.file.input)
    box(title="File Contents", width=12, solidHeader = TRUE, status="primary",
        div(datatable(data(), extensions = 'ColReorder', options = list(colReorder = TRUE,scrollX = TRUE)),style = "width: 100%;",align="center")
    )
  })
  
  output$covar.graph <- renderPlotly({
    req(input$data.file.input)
    lin.dat<-data()%>%
      filter(date<input$interventionrange[1])
    g<-ggplot(lin.dat, aes(x=response,y=!!input$covar.select))+geom_point()+geom_smooth(method = "lm", se = TRUE)+theme_bw()+ theme(panel.border = element_blank())
    ggplotly(g)
  })
  
  output$covar.graph.container<-renderUI({
    req(input$data.file.input)
    box(title="Variable Relationship", width=12, solidHeader = TRUE, status="primary",
        plotlyOutput("covar.graph")
    )
  })
  
  output$summary.stats<-renderUI({
    req(input$data.file.input)
    lin.dat<-data()%>%
      filter(date<input$interventionrange[1])
    
    mod<-lm(lin.dat$response~lin.dat[,toString(input$covar.select)])
    covar.cor<-cor(lin.dat$response,lin.dat[,toString(input$covar.select)])
    
    if(summary(mod)$r.squared<.3){
      r.color<-"red"
    }
    else if(summary(mod)$r.squared>=.3&&summary(mod)$r.squared<.65){
      r.color<-"yellow"
    }
    else{
      r.color<-"green"
    }
    
    if(abs(covar.cor)<.3){
      corr.color<-"red"
    }
    else if(abs(covar.cor)>=.3&&abs(covar.cor)<.65){
      corr.color<-"yellow"
    }
    else{
      corr.color<-"green"
    }
    covar.cor<-cor(lin.dat$response,lin.dat[,toString(input$covar.select)])
    tagList(
      box(title="Summary Statistics", width=12, solidHeader = TRUE, status="primary",
          h5("Percent of changes in Response explained by covariate (close to 1 is good)"),
          infoBox(width=12,
                  "R-Square",value=toString((round(summary(mod)$r.squared,3))), icon = icon("ok", lib = "glyphicon"),
                  color = r.color
          ),
          h5("Correlation between Response and covariate (close to 1 is good)"),
          infoBox(width=12,
                  "Correlation",value=round(covar.cor,3), icon = icon("ok", lib = "glyphicon"),
                  color = corr.color
          )
      )
    )
  })
  
  output$covariate.select<-renderUI({
    req(input$data.file.input)
    tagList(
      box(title="Select a Covariate", width=12, solidHeader = TRUE, status="primary",
          varSelectInput("covar.select", label=NULL, covar.data())
      )
    )
  })
  
  output$covariate.explanation<-renderUI({
    req(input$data.file.input)
    tagList(
      box(title="How to use this screen", width=12, solidHeader = TRUE, status="primary",
          tags$b("What should I look for in a good predictive covariate?"),
          p("A good predictive covariate should have a high correlation with and explain a large amount of the variance in the response variable (high R-Square metric)."),
          tags$b("Covariate requirements"),
          p("Control covariates should be relevant, relatively stable throughout the intervention period, and unaffected by the treatment. If a covariate does not meet these criteria, there is a danger of falsely under- or overestimating the true effect or falsely concluding that there was an effect even though in reality there wasn’t.")
      )
    )
  })
  
  output$impact.original.plot <- renderPlotly({
    req(input$data.file.input)
    x <- list(
      title = "Date"
    )
    y <- list(
      title = "Total Customer Transactions"
    )
    plot_ly(fortify.zoo(impact()$series), x=~Index, y= ~response, type = 'scatter', mode='lines', name="Actual")%>%
      layout(xaxis = x, yaxis = y,shapes = list(vline(toString(input$interventionrange[1])),vline(toString(input$interventionrange[2]))))%>%
      add_trace(y = ~point.pred, name = 'Expected', line = list(color = 'rgb(22, 96, 167)', width = 2, dash = 'dot'))  %>%
      add_ribbons(data=fortify.zoo(impact()$series),ymin=~point.pred.lower, ymax=~point.pred.upper,line = list(color = 'rgba(7, 80, 181, 0.05)'),fillcolor = 'rgba(7, 80, 181, 0.2)',name = '95% Prediction')
  })
  
  output$impact.daily.plot <- renderPlotly({
    req(input$data.file.input)
    x <- list(
      title = "Date"
    )
    y <- list(
      title = "Daily Incremental Value"
    )
    plot_ly(fortify.zoo(impact()$series), x=~Index, y= ~point.effect, type = 'scatter', mode='lines', name="Actual")%>%
      layout(shapes = list(vline(toString(input$interventionrange[1])),vline(toString(input$interventionrange[2]))))%>%
      add_ribbons(data=fortify.zoo(impact()$series),ymin=~point.effect.lower, ymax=~point.effect.upper,line = list(color = 'rgba(7, 80, 181, 0.05)'),fillcolor = 'rgba(7, 80, 181, 0.2)',name = '95% Prediction')
    
  })
  
  output$impact.cumulative.plot <- renderPlotly({
    req(input$data.file.input)
    x <- list(
      title = "Date"
    )
    y <- list(
      title = "Cumulative Incremental Value"
    )
    plot_ly(fortify.zoo(impact()$series), x=~Index, y= ~cum.effect, type = 'scatter', mode='lines', name="Actual")%>%
      layout(shapes = list(vline(toString(input$interventionrange[1])),vline(toString(input$interventionrange[2]))))%>%
      add_ribbons(data=fortify.zoo(impact()$series),ymin=~cum.effect.lower, ymax=~cum.effect.upper,line = list(color = 'rgba(7, 80, 181, 0.05)'),fillcolor = 'rgba(7, 80, 181, 0.2)',name = '95% Prediction')
    
  })
  
  output$impact.plot.output<-renderUI({
    req(input$data.file.input)
    box(title="Inpact Plots", width=12, solidHeader = TRUE, status="primary",
        tabsetPanel(type = "tabs",
                    tabPanel("Original/Predicted Series", plotlyOutput("impact.original.plot")),
                    tabPanel("Daily Impact", plotlyOutput("impact.daily.plot")),
                    tabPanel("Cumulative Impact", plotlyOutput("impact.cumulative.plot"))
        )
    )
    
  })
  
  output$impact.table.output <- renderDataTable({
    datatable(impact(),options = list(colReorder = TRUE,scrollX = TRUE))
    
  })
  
  output$impact.metrics <- renderUI({
    req(input$data.file.input)
    out<-tags$p(paste(round(as.numeric(impact()$summary$AbsEffect[2]),0)), style = "font-size: 200%;")
    out2<-tags$p(paste("  95% Conf. Interval [",round(as.numeric(impact()$summary$AbsEffect.lower[2]),0),"-",round(as.numeric(impact()$summary$AbsEffect.upper[2]),0),"]"), style = "font-size: 100%; font-weight: normal;")
    finalout<-paste0(out, out2)
    
    out.perc<-tags$p(paste(round(as.numeric(impact()$summary$RelEffect[2]),4)*100,"%"), style = "font-size: 200%; ")
    out2.perc<-tags$p(paste("  95% Conf. Interval [",round(as.numeric(impact()$summary$RelEffect.lower[2]),4)*100,"% -",round(as.numeric(impact()$summary$RelEffect.upper[2]),4)*100,"% ]"), style = "font-size: 100%; font-weight: normal;")
    finalout.perc<-paste0(out.perc, out2.perc)
    
    box(title="Impact Metrics", width=12, solidHeader = TRUE, status="primary",
        infoBox("Total Incremental Effect",HTML(finalout), icon=icon("coins"), color="green", width=12),
        infoBox("Total Incremental Percentage Change",HTML(finalout.perc), icon=icon("coins"), color="green", width=12)
    )
  })
  
  output$impact.summary <- renderUI({
    box(title="Full Impact Report", width=12, solidHeader = TRUE, status="primary",
        p(HTML(gsub("\n","",impact()$report)))
    )
  })
}

shinyApp(ui, server)
